name: cloud_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - python=3.8.1
  - xarray=0.15.0
  - dask=2.10.1
  - zarr=2.4.0
  - fsspec=0.6.2
  - s3fs=0.4.0
  - matplotlib=3.1.3
prefix: C:\Users\gentemann\Miniconda3\envs\cloud_tutorial


