name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - jupyter=1.0.0
  - numpy=1.16.3
  - pandas=0.24.2
  - python=3.7.1
  - xarray=0.12.1
  - netcdf4=1.5.1.2
  - dask=1.2.2
prefix: C:\Users\gentemann\Miniconda3\envs\tutorialenv
